import type { Product } from "./types";

// Mock data để demo UI, sau này có thể thay bằng API thật.
export const productsMock: Product[] = [
  {
    id: "1",
    slug: "tai-khoan-cursor-ai",
    name: "Tài khoản Cursor AI - Lập trình cùng AI (Pro - Chính chủ)",
    category: "AI Công cụ AI",
    price: 350100,
    originalPrice: 527000,
    sold: 20925,
    badge: "-47%",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "2",
    slug: "tai-khoan-gamma-ai",
    name: "Tài khoản Gamma AI - Làm slide, tài liệu thông minh",
    category: "AI Công cụ AI",
    price: 151200,
    originalPrice: 320000,
    sold: 10234,
    badge: "-53%",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "3",
    slug: "nang-cap-youtube-premium",
    name: "Nâng cấp YouTube Premium - Cá nhân / Gia đình",
    category: "Giải trí",
    price: 367630,
    originalPrice: 499000,
    sold: 18902,
    badge: "HOT",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "4",
    slug: "tai-khoan-chatgpt-plus",
    name: "Tài khoản OpenAI ChatGPT Plus GPT-4/4.1",
    category: "AI Công cụ AI",
    price: 374250,
    originalPrice: 599000,
    sold: 17001,
    badge: "-38%",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "5",
    slug: "tai-khoan-spotify-premium",
    name: "Tài khoản Spotify Premium - Cá nhân chính chủ",
    category: "Giải trí",
    price: 98000,
    originalPrice: 150000,
    sold: 9580,
    image: "https://picsum.photos/200/300",
  },
  {
    id: "6",
    slug: "tai-khoan-higgsfield-ai",
    name: "Tài khoản Higgsfield AI - Tạo video AI chất lượng cao",
    category: "AI Công cụ AI",
    price: 151050,
    originalPrice: 310000,
    sold: 7120,
    badge: "-51%",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "7",
    slug: "tai-khoan-grok-ai",
    name: "Tài khoản xAI Grok - Truy cập bản mới nhất",
    category: "AI Công cụ AI",
    price: 144530,
    originalPrice: 280000,
    sold: 5340,
    badge: "NEW",
    image: "https://picsum.photos/200/300",
  },
  {
    id: "8",
    slug: "tai-khoan-capcut-pro",
    name: "Tài khoản CapCut Pro - Nâng cấp video chuyên nghiệp",
    category: "Làm việc",
    price: 120000,
    originalPrice: 240000,
    sold: 6200,
    image: "https://picsum.photos/200/300",
  },
];

